### ISSUE TITLE
Set up instructions clarification

### ISSUE THREAD

**Issue by myoung34** [github/codeql-action#105]
The docs mention using this in the workflow:

```
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
```

Is this mandatory? Are there side-effects to only using: `- uses: actions/checkout@v2`
