### ISSUE TITLE
##[error]Rate Limit Exceeded

### ISSUE THREAD

**Issue by JOSHUAJEBARAJ** [github/codeql-action#113]
I am trying to use the `Default-Codeql` Action given in the repo But When I try to use It throws me the below error on ` Initialize CodeQL` Stage

The Action Code that I am using 

```
name: "Code Scanning - Action"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
       # with:
          # Must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head of the pull request.
          # Only include this option if you are running this workflow on pull requests.
         # fetch-depth: 2

      # If this run was triggered by a pull request event then checkout
      # the head of the pull request instead of the merge commit.
      # Only include this step if you are running this workflow on pull requests.
      #- run: git checkout HEAD^2
       # if: ${{ github.event_name == 'pull_request' }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # Override language selection by uncommenting this and choosing your languages
        # with:
        #   languages: go, javascript, csharp, python, cpp, java

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #   make bootstrap
      #   make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
```

## Error Logs

````
PUT /repos/JOSHUAJEBARAJ/atlan-report/code-scanning/analysis/status - 403 in 131ms
##[error]init action failed: HttpError: Rate Limit Exceeded
````
The Link for the action 
[Link](https://github.com/JOSHUAJEBARAJ/atlan-report/runs/878477186?check_suite_focus=true)
