### ISSUE TITLE
source-root is not applied in SARIF output

### ISSUE THREAD

**Issue by meriouma** [github/codeql-action#1147]
I'm not sure if I got the doc wrong, but I have a project with multiple folders and when running CodeQL on a single sub-folder using `source-root` like this :
```
runs:
  using: composite
  steps:
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ inputs.languages }}
        source-root: packages/react

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: ${{ inputs.category }}
        checkout_path: packages/react # Tried with or without this
```

In the sarif output, the `artifactLocation.uri` properties are relative to `packages/react`, which once uploaded to Github code scanning, yields invalid paths in the repository, as they are relative from the `source-root`, instead of the repository root.

**Comment by edoardopirovano** [comment]
Greetings, many thanks for getting in touch with this question. That is indeed what the `source-root` option will do, and it is almost certainly not the option you want to be using. Is your goal to only scan files in the `packages/react` folder? If so, I would recommend using the `paths` property of the configuration file as documented [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan).

In particular, you'll want to make a file called `./.github/codeql/codeql-config.yml` (or add to your exist one if you already have it) that contains:
```yaml
paths:
  - packages/react
```
Then, in your `init` step do:
```yaml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ inputs.languages }}
        config-file: ./.github/codeql/codeql-config.yml
```
I hope that's helpful! Do let me know if that works for you or if you have any further questions.
