### ISSUE TITLE
Analysis upload fails with `rejecting SARIF, as there are more threadflow steps per result than allowed (19350 > 10000)`

### ISSUE THREAD

**Issue by mrc0mmand** [github/codeql-action#1245]
Hello!

Today I wanted to enhance our CodeQL scan in the [systemd](https://github.com/systemd/systemd/pull/24671) repo by using the `security-extended` and `security-and-quality` query sets, but after adding them the CodeQL action can no longer upload the result SARIF file:

```
Waiting for processing to finish
  Analysis upload status is pending.
  Analysis upload status is failed.
  Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more threadflow steps per result than allowed (19350 > 10000)
  Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more threadflow steps per result than allowed (19350 > 10000)
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/0c670bbf0414f39666df6ce8e718ec5662c21e03/lib/upload-lib.js:334:19)
      at async run (/home/runner/work/_actions/github/codeql-action/0c670bbf0414f39666df6ce8e718ec5662c21e03/lib/analyze-action.js:131:13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/0c670bbf0414f39666df6ce8e718ec5662c21e03/lib/analyze-action.js:221:9)
```

Example job: https://github.com/systemd/systemd/actions/runs/3053021449/jobs/4923112318

Configuration:

```yaml
---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: "CodeQL"

on:
  pull_request:
    branches:
      - main
      - v[0-9]+-stable
    paths:
      - '**/meson.build'
      - '.github/**/codeql*'
      - 'src/**'
      - 'test/**'
      - 'tools/**'
  push:
    branches:
      - main
      - v[0-9]+-stable

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.language }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      actions: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['cpp', 'python']

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Initialize CodeQL
      uses: github/codeql-action/init@0c670bbf0414f39666df6ce8e718ec5662c21e03
      with:
        languages: ${{ matrix.language }}
        queries: +security-extended,security-and-quality

    - run: sudo -E .github/workflows/unit_tests.sh SETUP

    - name: Autobuild
      uses: github/codeql-action/autobuild@0c670bbf0414f39666df6ce8e718ec5662c21e03

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@0c670bbf0414f39666df6ce8e718ec5662c21e03
```

Since the build & analysis finishes successfully and only the last step fails, I don't think this is an issue on our side - is there something which can be done to mitigate this or we're out of luck?

Thank you!

**Comment by aibaars** [comment]
Hello! Thanks for reporting this. The first thing to do would be to figure out which rules/alerts are causing the problem. As an immediate fix you could remove the problematic alerts using https://github.com/advanced-security/filter-sarif .

Could you `Re-run all jobs` on the workflow and toggle the `Enable [debug logging](https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)` checkbox? When the workflow finishes a debug artefact should have been uploaded. This artefact contains a `.sarif` file. The debug artefact is a relatively new feature, so you may need to adjust the SHA of the codeql-action steps in the workflow. Alternatively, you can set the [`output`](https://github.com/github/codeql-action/blob/fd4dc5bf31bec2a626bf9a89113359953a1fba43/analyze/action.yml#L8-L11) property of the `codeql-action/analyze` step to a folder name and use the `actions/upload` action to upload that folder as an artefact.

Once you obtained the SARIF file, could you run the following `jq` commands on it and post the output? 

```
cat FILE.sarif | jq  '.runs[].results[].ruleId' | sort | uniq -c
```

```
cat FILE.sarif | jq -rc '.runs[].results[] | {rule: .ruleId, file: .locations[0].physicalLocation.artifactLocation.uri, codeFlowsCount: (.codeFlows | length), threadFlowStepsCount: (.codeFlows | reduce .[]? as $item (0;  . + ($item.threadFlows[0].locations | length)))}' | jq -s -c 'sort_by(.threadFlowStepsCount) | .[]'
```

**Comment by mrc0mmand** [comment]
> Hello! Thanks for reporting this. The first thing to do would be to figure out which rules/alerts are causing the problem. As an immediate fix you could remove the problematic alerts using https://github.com/advanced-security/filter-sarif .
> 
> Could you `Re-run all jobs` on the workflow and toggle the **Enable [debug logging](https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)** checkbox? When the workflow finishes a debug artefact should have been uploaded. This artefact contains a `.sarif` file. The debug artefact is a relatively new feature, so you may need to adjust the SHA of the codeql-action steps in the workflow.

You were right, I had to use the main ref instead of the pinnes SHAs to get the artifacts, so thanks for that!

> 
> Once you obtained the SARIF file, could you run the following `jq` commands on it and post the output?
> 
> ```
> cat FILE.sarif | jq  '.runs[].results[].ruleId' | sort | uniq -c
> ```

```
$ cat cpp.sarif | jq  '.runs[].results[].ruleId' | sort | uniq -c
      1 "cpp/cleartext-storage-file"
     16 "cpp/commented-out-code"
      2 "cpp/complex-condition"
      2 "cpp/constant-comparison"
     36 "cpp/fixme-comment"
      4 "cpp/include-non-header"
      3 "cpp/inconsistent-null-check"
     70 "cpp/irregular-enum-init"
      1 "cpp/leap-year/unchecked-after-arithmetic-year-modification"
     92 "cpp/long-switch"
     33 "cpp/loop-variable-changed"
      1 "cpp/missing-case-in-switch"
      7 "cpp/missing-header-guard"
      1 "cpp/non-constant-format"
      1 "cpp/offset-use-before-range-check"
      1 "cpp/overrunning-write"
    137 "cpp/path-injection"
    293 "cpp/poorly-documented-function"
     25 "cpp/stack-address-escape"
      4 "cpp/suspicious-allocation-size"
      2 "cpp/system-data-exposure"
     19 "cpp/toctou-race-condition"
     43 "cpp/too-many-format-arguments"
      9 "cpp/trivial-switch"
    113 "cpp/unbounded-write"
      4 "cpp/uncontrolled-allocation-size"
     15 "cpp/uncontrolled-process-operation"
     81 "cpp/uninitialized-local"
     82 "cpp/unterminated-variadic-call"
      1 "cpp/unused-local-variable"
    183 "cpp/unused-static-function"
      3 "cpp/unused-static-variable"
     34 "cpp/world-writable-file-creation"
``` 



> ```
> cat FILE.sarif | jq -rc '.runs[].results[] | {rule: .ruleId, file: .locations[0].physicalLocation.artifactLocation.uri, codeFlowsCount: (.codeFlows | length), threadFlowStepsCount: (.codeFlows | reduce .[]? as $item (0;  . + ($item.threadFlows[0].locations | length)))}' | jq -s -c 'sort_by(.threadFlowStepsCount) | .[]'
> ```

https://gist.github.com/mrc0mmand/d516a60a02c2f15b9bbfeac9b589f8bd

In case a further inspection is needed, I also uploaded the SARIF file to https://mrc0mmand.fedorapeople.org/gh_2022-09-14-cpp.sarif

**Comment by aibaars** [comment]
The tail of the second `jq` command shows there are 3 alerts that exceed the limits:
```
{"rule":"cpp/unbounded-write","file":"src/libsystemd/sd-bus/sd-bus.c","codeFlowsCount":1208,"threadFlowStepsCount":14496}
{"rule":"cpp/path-injection","file":"src/test/test-fs-util.c","codeFlowsCount":606,"threadFlowStepsCount":15135}
{"rule":"cpp/unbounded-write","file":"src/basic/unit-name.c","codeFlowsCount":1211,"threadFlowStepsCount":19350}
```

You could try to add a  [advanced-security/filter-sarif ](https://github.com/advanced-security/filter-sarif) to filter out the  `cpp/unbounded-write` results for `src/libsystemd/sd-bus/sd-bus.c` and `src/basic/unit-name.c` and also the `cpp/path-injection` results for `src/test/test-fs-util.c`.

**Comment by aeisenberg** [comment]
There is a new feature in code-scanning that allows you to remove queries from the analysis. Using this feature should remove the queries that are causing the problems. The documentation for this feature has not yet been published, but I will explain how to use it here.

1. Create a custom configuration file, as explained here: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-a-custom-configuration-file
2. The file can be empty, except for a `query-filters` block, like this:

```yaml
query-filters:
    - exclude:
        id: 
          - cpp/unbounded-write
          - cpp/path-injection
```

That should be enough.
