### ISSUE TITLE
github/codeql-action@v2 is triggering a warning about `set-output`

### ISSUE THREAD

**Issue by jsoref** [github/codeql-action#1306]
https://github.com/check-spelling/codecov-action/actions/runs/3260340643/jobs/5353831247#step:2:784

```yaml
Artifact check-spelling-sarif has been successfully uploaded!
Run github/codeql-action/upload-sarif@v2
  with:
    sarif_file: /tmp/tmp.z3kCIazQ0q.sarif.json
    category: check-spelling
    checkout_path: .
    token: ***
    matrix: null
    wait-for-processing: true
  env:
    UPLOAD_SARIF: /tmp/tmp.z3kCIazQ0q.sarif.json
    result_code: 1
Uploading results
  Processing sarif files: ["/tmp/tmp.z3kCIazQ0q.sarif.json"]
  Uploading results
  Successfully uploaded results
```

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
