### ISSUE TITLE
Benefits of matrix versus languages separated by commas

### ISSUE THREAD

**Issue by PavelBansky** [github/codeql-action#1398]
I have noticed that `codeql.yml` action is using matrix strategy and splits the action into multiple runs.
I'm using comma separated list of languages instead. It seems to be a batter approach for more complex builds

```yml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp,javascript
```

Are there any pros and cons to matrix strategy vs. comma separated list of languages?

**Comment by aibaars** [comment]
The matrix strategy will run the jobs in parallel and should therefore be faster.

The comma separated list approach runs all the analyses in the same job. This can be handy for complex multi-language builds that are hard to split into separate parts per language. Note that this is only important for compiled languages such as C/C++, C#, Java, and Go.

Note that while the matrix strategy is faster, it tends to cost a little more compute time. For example if you have two languages, both take 4 minutes to analyze, then the "comma-separated-list" approach will take 8 minutes and cost 8 compute minutes. For the matrix case there is a bit of overhead of say 1 minute, so in this case the time to analyse will be 5 minutes, but the compute cost will be 10 minutes (two concurrent jobs of 4+1 each).

The overhead of parallel builds tends to be small and the benefit of quicker analysis time (less time waiting for a PR check) usually outweighs the higher cost. Therefore I'd recommend the matrix approach in most cases.

**Comment by Hongbo-Miao** [comment]
I had same questions, and I did some experiments. Hopefully it can help people who come here in future!

## Experiment 1: `matrix` with `fail-fast: false` (personally I like this one 😃)

```yaml
    strategy:
      fail-fast: false  # Note here is false, by default it is true if not provided
      matrix:
        language: [go, java, javascript, python, ruby]
    steps:
      # ...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
```

If one failed, the rest of them still can succeed
<img width="309" alt="image" src="https://user-images.githubusercontent.com/3375461/205515390-4a7cca2b-49bd-4840-a961-f012e4b33c80.png">

## Experiment 2: `matrix` with default `fail-fast: true`

```yaml
    strategy:
      matrix:
        language: [go, java, javascript, python, ruby]
    steps:
      # ...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
```

When one failed, the rest of jobs that not finish will be cancelled.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/3375461/205515590-db0ee2a5-6b90-4c1d-a6b8-ac1281e9ad48.png">


## Experiment 3: `languages` separated by commas

```yaml
    steps:
      # ...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go, java, javascript, python, ruby
```

If any fail, you won't be able to know which language caused failure until check the log.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/3375461/205515456-250ebcfd-ddbc-4f2d-8001-fb3d01ab765f.png">
