### ISSUE TITLE
Allowing Access to Private Repo

### ISSUE THREAD

**Issue by ItsHyperOS** [github/codeql-action#142]
I am not quite sure how to configure this. I have heard that I can use GITHUB_TOKEN authenticate. 

```
- name: Configuring GitHub Access
        env:
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          git config --global url."https://${TOKEN}@github.com/<Username>/<Repo Name>".insteadOf "https://github.com/<Username>/<Repo Name>"
```

Is this the right way to configure it?
