### ISSUE TITLE
Getting old CodeQL Version 2.12.2 instead of 2.12.3 on GitHub runner

### ISSUE THREAD

**Issue by PascalHonegger** [github/codeql-action#1555]
We're trying to setup CodeQL Scanning for a new Kotlin & Gradle project. We're facing a problem, because the action failes with the message `Kotlin 1.8.10` is too recent, but this was resolved in the latest CodeQL version `2.12.3`.

Looking at the log of the run (https://github.com/samtkit/core/actions/runs/4314385035/jobs/7527338644) we found the following lines in the output:
```
Found CodeQL tools version 2.12.2 in the toolcache.
/opt/hostedtoolcache/CodeQL/2.12.2-20230207/x64/codeql/codeql version --format=terse
2.12.2
```

It seems like our runner is still using an earlier version, is there any way we can force the new version? Do we just have to wait a few days or weeks until it gets rolled out everywhere?

**Comment by adityasharad** [comment]
We gradually roll out new CodeQL versions to the GitHub Actions tool cache and repos that do not explicitly specify which CodeQL tool versions they want to use.

If you'd like to use 2.12.3 right away, please try setting `tools: latest` in the `github/codeql-action/init@v2` step of your Actions workflow. This means your workflow will download the latest stable CodeQL version instead of using the cache. You can remove this setting in around 1 week, by which point 2.12.3 will have been rolled out by default.
```yaml
- name: Initialize CodeQL
  uses: github/codeql-action/init@v2
  with:
      tools: latest
      ... # other options as currently defined in your workflow
```
