### ISSUE TITLE
Upload multiple sarif files

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [github/codeql-action#1573]
Similar to `actions/upload-artifact`, `upload-sarif` should allow upload multiple sarif files. Pattern matching from `upload-artifact` should be great too.

**Comment by aeisenberg** [comment]
This is already available (except no pattern matching). The `sarif_file` accepts a directory. All files ending in `*.sarif` will be merged and uploaded. Is this what you are looking for?

**Comment by JavierSegoviaCordoba** [comment]
@aeisenberg I have all sarif fails on different directories. I could move them in a previous step but would be great if this feature was directly supported.

**Comment by aeisenberg** [comment]
This feature will recursively search the directory you pass it for sarif files.

**Comment by JavierSegoviaCordoba** [comment]
I can pass the root directory so it can check the whole project?

The files are on different folders at same level too so passing the root one is the only solution.

**Comment by aeisenberg** [comment]
I imagine that this should work. It will search all files in all subdirectories, so if you are talking about the root of the filesystem, this will search through a lot of files. I recommend that you try it out and see if it works for you.

**Comment by JavierSegoviaCordoba** [comment]
I tried the next one but it fails.

```
      - name: Upload Code Scanning code analysis report
        if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: '/'
```
