### ISSUE TITLE
How to send code scanning alerts direct into github issues

### ISSUE THREAD

**Issue by MohdRashid01** [github/codeql-action#1580]
Hi,

I have github action yml file in that i add below task in yml file and when jobs complete it send code scanning alerts direct into Security inside code scanning but we want to have that alerts to be shown in github issues not in security
```
   - name: upload sarif file to repository
         if: failure()
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: ./results.sarif 
```
Here is the screenshot of Security showing alerts
![image](https://user-images.githubusercontent.com/7812871/225269847-97f4e1a4-c972-4c3f-a224-2f5a39e478c9.png)

Here is the github issue which actually it should show
![image](https://user-images.githubusercontent.com/7812871/225269918-c7277e75-e8bf-4809-bc9e-f50f0bcba083.png)

We dont want to do manually but it should have automatically when the github action job trigger
