### ISSUE TITLE
Provide a way to pass a whole configuration as parameter

### ISSUE THREAD

**Issue by tgrall** [github/codeql-action#1589]
## Problem

As a user of GitHub CodeQL in Actions I would like to be able to pass some configuration when running my workflow, for example:
- pass a query filter from or environment variable or input parameter

Today only a subset of the available configuration/parameters is available in the action.

## Solution

Add a new parameter, for example called `configuration` that will take the same format as a `config-file` but can be used directly in the action.

The idea is to support the following examples:

- Complete on configuration
  ```yaml
  - uses: github/codeql-action/init@v2
    with:
      languages: ${{ matrix.language }}
      configuration: |
        disable-default-queries: true
        queries:
          - uses: security-extended
          - uses: security-and-quality
        query-filters:
          - include:
        tags: /cwe-020/
  ```

- Actions Variable
  ```yaml
  - uses: github/codeql-action/init@v2
    with:
      languages: ${{ matrix.language }}
      configuration: |
            ${{vars.CODEQL_CONF}}    
  ```

- Input Parameter
    ```yaml
      - uses: tgrall/codeql-action/init@query-filter
      with:
        languages: ${{ matrix.language }}
        configuration: |
          disable-default-queries: true
          queries:
            - uses: security-extended
            - uses: security-and-quality
          query-filters:
            - include:
                tags: /${{ github.event.inputs.codeql-include-tags }}/ 
   ```
