### ISSUE TITLE
`github/codeql-action/analyze` should offer an output for the sarif path

### ISSUE THREAD

**Issue by jsoref** [github/codeql-action#1799]
There's an input for the output:
https://github.com/github/codeql-action/blob/57a11be8e4a40671215b59c4a6c5f7f82df48934/analyze/action.yml#L4
https://github.com/github/codeql-action/blob/57a11be8e4a40671215b59c4a6c5f7f82df48934/analyze/action.yml#L8-L11

But there is no output for the sarif file path:
https://github.com/github/codeql-action/blob/57a11be8e4a40671215b59c4a6c5f7f82df48934/analyze/action.yml#L79-L83

The output file defaults to `../results` which isn't accepted by actions/upload-artifact:
https://github.com/jsoref/pdns/actions/runs/5657547911/job/15326842548#step:12:4
https://github.com/jsoref/pdns/actions/runs/5657547911/job/15326842548#step:12:48

```yml
Run actions/upload-artifact@v3
  with:
    name: sarif
    path: ../results
    if-no-files-found: warn
...
Error: Invalid pattern '../results'. Relative pathing '.' and '..' is not allowed.
```
