### ISSUE TITLE
codeql/upload-sarif@v2 or @main can't integrate on actions

### ISSUE THREAD

**Issue by archermask** [github/codeql-action#1806]
![image](https://github.com/github/codeql-action/assets/140574016/d666c966-29e0-4c7e-a756-e670016fc944)

The error is `Error: codeql/upload-sarif action failed: Resource not accessible by integration`
My case is try to integrate snyk for sast on my golang code, and then upload sarif file to github to look any vulnerabilities summary. 

My workflow actions yaml files:
```
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Unit test
      continue-on-error: false 
      run: go test ./...
      
    - name: SAST Test
      uses: snyk/actions/golang@master
      continue-on-error: true 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --sarif-file-output=snyk.sarif
    
    - name: Upload SAST Test Result
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
```
