### ISSUE TITLE
Error: Invalid SARIF. JSON syntax error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by digitalghost-dev** [github/codeql-action#2546]
I am trying to use the `github/codeql-action/upload-sarif@v3` action in my GitHub Actions CI pipeline but am running into an issue:

```
Error: Invalid SARIF. JSON syntax error: Unexpected end of JSON input
```

I am using `syft` to create a `SBOM` and upload it as an artifact. Then, I am using `grype` to scan the `SBOM` and then upload a error report as a `SARIF` file:

<details>
  <summary>yaml file example</summary>

  ```yaml
    syft:
      permissions:
        contents: 'read'
        id-token: 'write'
  
      runs-on: ubuntu-22.04
      needs: [build-docker-image]
      if: needs.build-docker-image.result == 'success'
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Set up Docker Buildx
          uses: 'docker/setup-buildx-action@v3.0.0'
  
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: poke-cli
            path: /tmp
  
        - name: Load Image
          run: |
            docker load --input /tmp/poke-cli.tar
            docker image ls -a
  
        - name: Create and Upload SBOM
          uses: anchore/sbom-action@v0
          with:
            image: poke-cli:${{ env.VERSION_NUMBER }}
            path: /tmp
            format: spdx-json
            artifact-name: poke-cli-sbom-${{ env.VERSION_NUMBER }}.spdx.json
            upload-artifact: true
  
    grype:
      permissions:
        actions: read
        contents: read
        security-events: write
  
      runs-on: ubuntu-22.04
      needs: [syft]
      if: needs.syft.result == 'success'
  
      steps:
        - name: Download SBOM
          uses: actions/download-artifact@v4
          with:
            name: poke-cli-sbom-${{ env.VERSION_NUMBER }}.spdx.json
            path: /tmp
  
        - name: Scan SBOM
          uses: anchore/scan-action@v3
          id: scan
          with:
            sbom: poke-cli-sbom-${{ env.VERSION_NUMBER }}.spdx.json
            fail-build: false
            output-format: sarif
            severity-cutoff: critical
  
        - name: Upload SARIF Report
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: ${{ steps.scan.outputs.sarif }}
  ```
</details>

The artifact is uploaded and there is data in there when I download it and open up the `spdx.json` file so not sure what else could be the problem.
