### ISSUE TITLE
go build hangs after codeql init

### ISSUE THREAD

**Issue by csandanov** [github/codeql-action#2589]
Hi, 

I'm trying out codeql, after running codeql init for go language and with the debug flag I build my app with `go build -x` and it just hangs, no output. I use the same steps to build my app in a separate workflow where there's no codeql and it works just fine. Running locally with codeql CLI (macos arm64) also works.

My workflow (simplified):

```yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
          debug: true

      - name: Build app
        run: go build -x

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
```

I tried autobuild but after a few minutes it just hangs on one of the go files and I don't know why, would be great to learn how can I debug this. 

Thank you.

**Comment by Aze331** [comment]
Hey,

I was experiencing similar issues on GHES, but I added:

`tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.19.2/codeql-bundle-linux64.tar.gz`

in
          
```
- name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ${{ inputs.codeql-cfg-path }}
          tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.19.2/codeql-bundle-linux64.tar.gz
``` 

This resolved the issue. I'm not sure what the rootcause was because it worked on another Selfhosted runner I tried it on.

Could likely be related to the change from gzip to Zstandard https://github.com/github/codeql-action/pull/2573
