### ISSUE TITLE
After completing the CodeQL check it showing in progress state

### ISSUE THREAD

**Issue by AjitPadhi-Microsoft** [github/codeql-action#2661]
Below workflow code having issue even after completing the CodeQL stage
```
name: "CodeQL Advanced"

on:
push:
branches: [main]
pull_request:
branches: [main]

jobs:
analyze:
name: Analyze (${{ matrix.language }})

runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
permissions:
  security-events: write
  packages: read
  actions: read
  contents: read

strategy:
  fail-fast: false
  matrix:
    include:
    - language: javascript-typescript
      build-mode: none 
    - language: python
      build-mode: none
    
steps:
- name: Checkout repository
  uses: actions/checkout@v4

# Initializes the CodeQL tools for scanning.
- name: Initialize CodeQL
  uses: github/codeql-action/init@v3
  with:
    languages: ${{ matrix.language }}
    build-mode: ${{ matrix.build-mode }}
    config-file: .github/codeql/codeql-config.yml
    queries: security-extended

- name: Perform CodeQL Analysis
  id: analyze
  uses: github/codeql-action/analyze@v3
  with:
    category: "/language:${{matrix.language}}"
    ```
Attached image for reference
<img width="365" alt="image" src="https://github.com/user-attachments/assets/e0c803da-b53d-403b-a88f-6ff1b63e7e18" />
![Uploading Screenshot 2024-12-20 160010.png…]()

<img width="365" alt="image" src="https://github.com/user-attachments/assets/e0c803da-b53d-403b-a88f-6ff1b63e7e18" />
