### ISSUE TITLE
upload-sarif failure...

### ISSUE THREAD

**Issue by xengine-qyt** [github/codeql-action#2694]
Error: Aborting upload: only one run of the codeql/analyze or codeql/upload-sarif actions is allowed per job per tool/category. The easiest fix is to specify a unique value for the `category` input. If .runs[].automationDetails.id is specified in the sarif file, that will take precedence over your configured `category`. Category: (/language:c-cpp/) Tool: (CodeQL)

here is my codeql yml:
```
name: CodeQL Advanced

on:
  push:
    branches: 
      - 'master'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Checkout dependency repository (xengine)
      uses: actions/checkout@v4
      with:
        repository: libxengine/libxengine
        path: libxengine

    - name: sub module checkout (opensource)
      run: |
          git submodule init
          git submodule update

    - name: Set up Dependency Environment
      run: |
          cd libxengine
          chmod +x ./XEngine_LINEnv.sh
          sudo ./XEngine_LINEnv.sh -i 3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        
    - name: make
      run: | 
          cd XEngine_Source
          make

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: "cpp-analysis"
```
I don't understand why it keeps reporting errors.
My other actions scripts only do the compilation, not the codeql. I don't see where the conflict is.
