### ISSUE TITLE
No way to configure CODEQL_THREADS with an environment variable

### ISSUE THREAD

**Issue by austinpray-mixpanel** [github/codeql-action#2890]
The source says this action respects both CODEQL_RAM and CODEQL_THREADS

https://github.com/github/codeql-action/blob/5eb3ed6614230b1931d5c08df9e096e4ba524f21/lib/init-action.js#L315C12-L319

this is true for CODEQL_RAM

https://github.com/github/codeql-action/blob/5eb3ed6614230b1931d5c08df9e096e4ba524f21/lib/init-action.js#L320

but not true for CODEQL_THREADS

https://github.com/github/codeql-action/blob/5eb3ed6614230b1931d5c08df9e096e4ba524f21/lib/init-action.js#L322

Is this an oversight or is there a good reason for this?

My use case is I'm running this on a big 48 core kubernetes but the codeql runner pod is only allowed to use 16 cores. The autodetection is not factoring in the pod limits, it's looking at the node's available resources. I want to hint to codeql that it only has 16 threads available via the CODEQL_THREADS env var.

**Comment by austinpray-mixpanel** [comment]
Spiked up a PR for this https://github.com/github/codeql-action/pull/2891

**Comment by mbg** [comment]
> The source says this action respects both CODEQL_RAM and CODEQL_THREADS

I think there's a key misunderstanding here: the comment in https://github.com/github/codeql-action/blob/5eb3ed6614230b1931d5c08df9e096e4ba524f21/src/init-action.ts#L538-L542 talks about the CodeQL _CLI_, not the CodeQL _Action_. In other words, it is the _CLI_ that respects these environment variables and they are set by the _Action_ based on the corresponding Actions inputs (if set).

That said, I am unsure why we respect the existing value of `CODEQL_RAM` (if set) over the explicit input to the Action and not `CODEQL_THREADS` (if set).

**Comment by austinpray-mixpanel** [comment]
Thank you for the quick response!

More concrete details:

```yaml
name: "GHAS JS CodeQL"

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.html'
      - '.github/workflows/ghas-js-codeql.yaml'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.html'
      - '.github/workflows/ghas-js-codeql.yaml'
  workflow_dispatch: {}

jobs:
  analyze:
    name: Analyze
    runs-on: 'mxpnl-arc-32' # needs upsized runner or will OOM
    container:
      image: '<an ubuntu 24.04 base image>'
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 30
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4.3.0
      with:
        node-version-file: .nvmrc

    # Initializes the CodeQL tools for scanning.
    - name: print env vars
      run: |
        echo "CODEQL_THREADS=$CODEQL_THREADS"
        echo "CODEQL_RAM=$CODEQL_RAM"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3.28.14
      with:
        languages: javascript-typescript
        build-mode: none
        config-file: ./.github/codeql-config.yaml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3.28.14
      with:
        category: "/language:javascript-typescript"
```

mxpnl-arc-32 is a actions-runner-controller autoscaling runner set in kubernetes mode where the workflow pods have these env vars set
![Image](https://github.com/user-attachments/assets/242c3314-649b-4efc-9010-029c93400515)

nets me 

![Image](https://github.com/user-attachments/assets/19ab718a-441b-41bb-8fe7-164a52c18b94)

![Image](https://github.com/user-attachments/assets/b6f5df3c-1a44-4274-890f-3f7c7a83470f)

So it's correctly picking up the ram variable but ignoring the threads env var.

![Image](https://github.com/user-attachments/assets/c208c061-a2e5-47ec-91d4-88b39b452d9c)

The CLI is not respecting the global env var because it is being overridden by the action

**Comment by mbg** [comment]
Like I said, you would need to set the environment variable(s) for the `analyze` step. They get overriden by the `init` step as you say, but you can set them yourself for the `analyze` step with e.g.:

```yaml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3.28.14
      with:
        category: "/language:javascript-typescript"
      env:
        CODEQL_THREADS: # your value or expression here
```

**Comment by austinpray-mixpanel** [comment]
I'm still a little confused why we can't unify the behavior of the CODEQL_THREAD env var with the CODEQL_RAM env var. Like what's the downside to making them behave in the same way?

I'm rolling with updating each of our GHAS workflows with a step to pass the environment vars to the init step explicitly 

```yaml
name: "GHAS JS CodeQL"
# ...
jobs:
  analyze:
    # ...
    steps:
    # ...
    # 👉 added this step to pass the env vars to the init action
    - name: Set limit vars
      run: |
        echo "CODEQL_THREADS=$CODEQL_THREADS" >> "$GITHUB_ENV"
        echo "CODEQL_RAM=$CODEQL_RAM" >> "$GITHUB_ENV"
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3.28.14
      with:
        languages: javascript-typescript
        build-mode: none
        config-file: ./.github/codeql-config.yaml
        threads: ${{ env.CODEQL_THREADS }}
        ram: ${{ env.CODEQL_RAM }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3.28.14
      with:
        category: "/language:javascript-typescript"
```
