### ISSUE TITLE
upload-sarif does not handle relative paths when trivy runs on a subfolder

### ISSUE THREAD

**Issue by rofreytag** [github/codeql-action#2904]
_Originally posted by @rofreytag in [#2215](https://github.com/github/codeql-action/issues/2215#issuecomment-2901199211)_

I run into an issue when using trivy config scan on a subfolder. The reported issues appear in the security tab, but the folder/path reference of files inside the repo is not correctly presented.

Example finding: 

<img width="930" alt="Image" src="https://github.com/user-attachments/assets/3e6d366b-8328-4292-92d1-2f0fbb1ec6c7" />

The expected path should be `terraform/01-bootstrap/eks.tf`.

The generated sarif file by trivy:
- uses URLs relative to `terraform/some-module` (i.e. `main.tf`)
- uses relative URLs for module invocations like `../modules/other-module/main.tf`. 
- includes the correct `uriBaseId`

GitHub interprets all these URls relative to the repo root without using `uriBaseId`. 

I am happy to try a workaround, but currently
- I can not yet find a way to make trivy generate _absolute_ URLs, which I believe resolves the issue. 
- Neither can I tell the upload-action that I am using relative URLs in my repo

## expected behavior
Either have the upload-action use the `uriBaseId` of the sarif file, or

have an existing param like [checkout_path](https://github.com/github/codeql-action/blob/c2c0a2908e95769d01b907f9930050ecb5cf050d/analyze/action.yml#L44-L47) (or a new param) in the action, to respect and transform relative URLs, so that they correctly appear in the report.

Example: 
```
     - name: Upload Trivy scan results to GitHub Security tab
       uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
       with:
         sarif_file: 'trivy-results.sarif'
         category: trivy-my-module
         checkout_path: ${{ github.workspace }}/terraform/01-bootstrap/
```

Here an excerpt of the generated sarif file that shows the URLs of each finding
```
          "message": {
            "text": "Artifact: eks.tf\nType: terraform\nVulnerability aws-vpc-add-description-to-security-group-rule\nSeverity: LOW\nMessage: Security group rule does not have a description.\nLink: [aws-vpc-add-description-to-security-group-rule](https://avd.aquasec.com/misconfig/aws-vpc-add-description-to-security-group-rule)"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "eks.tf",
                  "uriBaseId": "ROOTPATH"
                },

          "message": {
            "text": "Artifact: ../modules/rdb/main.tf\nType: terraform\nVulnerability AVD-AWS-0098\nSeverity: LOW\nMessage: Secret explicitly uses the default key.\nLink: [AVD-AWS-0098](https://avd.aquasec.com/misconfig/avd-aws-0098)"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "../modules/rdb/main.tf",
                  "uriBaseId": "ROOTPATH"
                },
```
and the originalUriBaseId section at the end:
```
      "originalUriBaseIds": {
        "ROOTPATH": {
          "uri": "file:///home/runner/work/redacted/redacted/terraform/01-bootstrap/"
        }
      }
    }
  ]
}
```

Here is my full workflow file
```
name: Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '27 23 * * 2'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  analyze-tf:
    runs-on: ubuntu-latest
    name: Analyze (${{ matrix.config.path }})
    strategy:
      matrix:
        config:
        - path: terraform/00-shared
          varfile: configs/sai-shared-prod.tfvars
        - path: terraform/01-bootstrap
          varfile: configs/sai-prod.tfvars
        - path: terraform/02-k8s
          varfile: configs/sai-prod.tfvars
        - path: terraform/03-services
          varfile: configs/sai-prod.tfvars

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 #v0.30.0
        with:
          scan-type: 'config'
          scan-ref: ${{ matrix.config.path }}
          tf-vars: ${{ matrix.config.path }}/${{ matrix.config.varfile }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          version: v0.61.1

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: 'trivy-results.sarif'
          # need to add unique category, so the results in one commit do not overwrite each other
          category: trivy-${{ matrix.config.path }}
          # I tried this with no luck
          # checkout_path: ${{ github.workspace }}/${{ matrix.config.path }}/

```

**Comment by rofreytag** [comment]
I understand @jketema - the issue is that we do not have a workaround. It seems the upload action should allow for something (like a path param) to enable this. At this point, I can only attempt to write some custom script to preprocess the sarif file before upload.

Note that the GitHub sales team recommended trivy to us in the context of enabling Advanced Security in our enterprise.

**Comment by noqt** [comment]
I tried the caller-side preprocessing approach against a synthetic SARIF reproducing the two path shapes in this issue. With `--scan-subdir terraform/01-bootstrap`, it maps:

- `eks.tf` → `terraform/01-bootstrap/eks.tf`
- `../modules/rdb/main.tf` → `terraform/modules/rdb/main.tf`

Here is the exact built-ins-only Node script I exercised:

<details>
<summary><code>normalize-sarif.mjs</code></summary>

```js
#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const hasOwn = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
const CONTROL_CHARACTER = /[\u0000-\u001f\u007f]/;
const URI_SCHEME = /^[A-Za-z][A-Za-z0-9+.-]*:/;

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function reject(message) {
  throw new Error(message);
}

function walk(value, visitor, location = '$') {
  visitor(value, location);
  if (Array.isArray(value)) {
    value.forEach((child, index) => walk(child, visitor, `${location}[${index}]`));
    return;
  }
  if (!isRecord(value)) return;
  for (const [key, child] of Object.entries(value)) {
    walk(child, visitor, `${location}.${key}`);
  }
}

function validatePathSyntax(value, label) {
  if (typeof value !== 'string' || value.length === 0) {
    reject(`${label} must be a nonempty relative POSIX path`);
  }
  if (CONTROL_CHARACTER.test(value)) {
    reject(`${label} contains a control character`);
  }
  if (value.includes('\\')) {
    reject(`${label} contains a backslash; only POSIX separators are supported`);
  }
  if (value.startsWith('/')) {
    reject(`${label} is absolute; repository-relative paths are required`);
  }
  if (URI_SCHEME.test(value)) {
    reject(`${label} has a URI scheme or drive prefix`);
  }
  if (value.includes('?') || value.includes('#') || value.includes('%')) {
    reject(`${label} contains URI/query encoding that this small subset does not accept`);
  }
  const segments = value.split('/');
  if (segments.some((segment) => segment.length === 0)) {
    reject(`${label} contains an empty path segment`);
  }
  if (segments.some((segment) => segment === '.')) {
    reject(`${label} contains an ambiguous '.' path segment`);
  }
  return segments;
}

function validateScanSubdir(scanSubdir) {
  const segments = validatePathSyntax(scanSubdir, '--scan-subdir');
  if (segments.some((segment) => segment === '..')) {
    reject('--scan-subdir must already be repository-relative and cannot contain ..');
  }
  return segments;
}

function normalizeScanRelativeUri(uri, scanSegments, label) {
  const segments = validatePathSyntax(uri, label);
  const output = scanSegments.slice();
  for (const segment of segments) {
    if (segment === '..') {
      if (output.length === 0) {
        reject(`${label} escapes the repository after joining with --scan-subdir`);
      }
      output.pop();
    } else {
      output.push(segment);
    }
  }
  if (output.length === 0) {
    reject(`${label} resolves to the repository root, not a nonempty artifact path`);
  }
  return output.join('/');
}

function validateRepositoryRelativeUri(uri, label) {
  const segments = validatePathSyntax(uri, label);
  if (segments.some((segment) => segment === '..')) {
    reject(`${label} is not a normalized repository-relative path`);
  }
  return segments.join('/');
}

function validateRootPathBase(base, label) {
  if (!isRecord(base) || !hasOwn(base, 'uri') || typeof base.uri !== 'string' || base.uri.length === 0) {
    reject(`${label} must be an object with a nonempty file URI`);
  }
  if (hasOwn(base, 'index') || hasOwn(base, 'uriBaseId')) {
    reject(`${label} uses an unsupported index or nested uriBaseId shape`);
  }
  const uri = base.uri;
  if (CONTROL_CHARACTER.test(uri) || uri.includes('\\') || uri.includes('%') || uri.includes('?') || uri.includes('#')) {
    reject(`${label}.uri has unsupported URI syntax`);
  }
  if (!uri.startsWith('file:///') || !uri.endsWith('/')) {
    reject(`${label}.uri must be an absolute file URI ending in '/'`);
  }
  const rawPath = uri.slice('file:///'.length);
  if (rawPath.length > 0) {
    const rawSegments = rawPath.split('/');
    rawSegments.pop();
    if (rawSegments.some((segment) => segment.length === 0 || segment === '.' || segment === '..')) {
      reject(`${label}.uri contains an ambiguous path segment`);
    }
    if (/^[A-Za-z]:$/.test(rawSegments[0] ?? '')) {
      reject(`${label}.uri uses an unsupported Windows drive path`);
    }
  }
  let parsed;
  try {
    parsed = new URL(uri);
  } catch {
    reject(`${label}.uri is not a valid file URI`);
  }
  if (parsed.protocol !== 'file:' || parsed.host !== '' || parsed.search || parsed.hash || !parsed.pathname.startsWith('/')) {
    reject(`${label}.uri must use the local file:// scheme without a host, query, or fragment`);
  }
  if (/^\/[A-Za-z]:\//.test(parsed.pathname)) {
    reject(`${label}.uri uses an unsupported Windows drive path`);
  }
  if (parsed.pathname !== '/') {
    const segments = parsed.pathname.split('/').slice(1, -1);
    if (segments.some((segment) => segment.length === 0 || segment === '.' || segment === '..')) {
      reject(`${label}.uri contains an ambiguous path segment`);
    }
  }
}

function inspectMetadata(sarif) {
  let rootBaseCount = 0;
  let rootReferenceCount = 0;
  walk(sarif, (value, location) => {
    if (isRecord(value) && hasOwn(value, 'partialFingerprints')) {
      reject(`pre-existing partialFingerprints are unsupported (${location}.partialFingerprints)`);
    }
    if (isRecord(value) && hasOwn(value, 'originalUriBaseIds') && isRecord(value.originalUriBaseIds)) {
      if (hasOwn(value.originalUriBaseIds, 'ROOTPATH')) {
        rootBaseCount += 1;
        validateRootPathBase(value.originalUriBaseIds.ROOTPATH, `${location}.originalUriBaseIds.ROOTPATH`);
      }
    }
    if (isRecord(value) && hasOwn(value, 'uriBaseId') && value.uriBaseId === 'ROOTPATH') {
      rootReferenceCount += 1;
    }
  });
  if (rootReferenceCount > 0 && rootBaseCount === 0) {
    reject('ROOTPATH is referenced but no supported originalUriBaseIds.ROOTPATH base is present');
  }
}

function normalizeArtifactLocation(artifactLocation, scanSegments, location) {
  if (!isRecord(artifactLocation)) {
    reject(`${location} must be an artifactLocation object`);
  }
  if (hasOwn(artifactLocation, 'index')) {
    reject(`${location}.index is unsupported; index-only and mixed artifact locations are rejected`);
  }
  if (!hasOwn(artifactLocation, 'uri') || typeof artifactLocation.uri !== 'string' || artifactLocation.uri.length === 0) {
    reject(`${location} must contain a nonempty uri; index-only locations are unsupported`);
  }
  if (hasOwn(artifactLocation, 'uriBaseId')) {
    if (artifactLocation.uriBaseId !== 'ROOTPATH') {
      reject(`${location}.uriBaseId must be ROOTPATH in the supported input subset`);
    }
    artifactLocation.uri = normalizeScanRelativeUri(artifactLocation.uri, scanSegments, `${location}.uri`);
    delete artifactLocation.uriBaseId;
    return;
  }
  // This is the idempotent form emitted by this CLI. It must already be canonical.
  artifactLocation.uri = validateRepositoryRelativeUri(artifactLocation.uri, `${location}.uri`);
}

function inspectArtifactLocationMode(sarif) {
  let mode = null;
  walk(sarif, (value, location) => {
    if (!isRecord(value) || !hasOwn(value, 'artifactLocation')) return;
    const artifactLocation = value.artifactLocation;
    if (!isRecord(artifactLocation)) return;
    const currentMode = hasOwn(artifactLocation, 'uriBaseId') ? 'ROOTPATH' : 'normalized';
    if (mode !== null && mode !== currentMode) {
      reject(`mixed ROOTPATH and already-normalized artifact locations are ambiguous (${location}.artifactLocation)`);
    }
    mode = currentMode;
  });
}

function transformArtifactLocations(sarif, scanSegments) {
  walk(sarif, (value, location) => {
    if (isRecord(value) && hasOwn(value, 'artifactLocation')) {
      normalizeArtifactLocation(value.artifactLocation, scanSegments, `${location}.artifactLocation`);
    }
  });
}

function hasRootPathReferences(sarif) {
  let found = false;
  walk(sarif, (value) => {
    if (found) return;
    if (isRecord(value) && hasOwn(value, 'uriBaseId') && value.uriBaseId === 'ROOTPATH') {
      found = true;
    }
  });
  return found;
}

function removeUnusedRootPathBases(sarif) {
  if (hasRootPathReferences(sarif)) return;
  walk(sarif, (value) => {
    if (!isRecord(value) || !isRecord(value.originalUriBaseIds)) return;
    if (hasOwn(value.originalUriBaseIds, 'ROOTPATH')) {
      delete value.originalUriBaseIds.ROOTPATH;
    }
  });
}

export function normalizeSarif(sarif, scanSubdir) {
  if (!isRecord(sarif)) reject('input must be a SARIF object');
  if (sarif.version !== '2.1.0') reject('only SARIF version 2.1.0 is supported');
  if (!Array.isArray(sarif.runs) || sarif.runs.length === 0) reject('SARIF runs must be a nonempty array');
  if (sarif.runs.some((run) => !isRecord(run))) reject('every SARIF run must be an object');
  const scanSegments = validateScanSubdir(scanSubdir);
  inspectMetadata(sarif);
  inspectArtifactLocationMode(sarif);
  transformArtifactLocations(sarif, scanSegments);
  removeUnusedRootPathBases(sarif);
  return sarif;
}

function parseArguments(argv) {
  if (argv.length !== 4 || argv[0] !== '--scan-subdir') {
    reject('usage: node normalize-sarif.mjs --scan-subdir <repository/scan/subdir> input.sarif output.sarif');
  }
  return { scanSubdir: argv[1], inputPath: argv[2], outputPath: argv[3] };
}

export function runCli(argv = process.argv.slice(2)) {
  const { scanSubdir, inputPath, outputPath } = parseArguments(argv);
  const source = fs.readFileSync(inputPath, 'utf8');
  let sarif;
  try {
    sarif = JSON.parse(source);
  } catch (error) {
    reject(`input is not valid JSON: ${error.message}`);
  }
  const normalized = normalizeSarif(sarif, scanSubdir);
  fs.writeFileSync(outputPath, `${JSON.stringify(normalized, null, 2)}\n`, 'utf8');
}

const thisFile = path.resolve(fileURLToPath(import.meta.url));
if (process.argv[1] && path.resolve(process.argv[1]) === thisFile) {
  try {
    runCli();
  } catch (error) {
    console.error(`normalize-sarif: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
```

</details>

Run it between Trivy and `upload-sarif`:

```yaml
- name: Normalize SARIF paths to repository root
  run: node normalize-sarif.mjs --scan-subdir "${{ matrix.config.path }}" trivy-results.sarif trivy-results.repo.sarif

- name: Upload Trivy scan results
  uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f
  with:
    sarif_file: trivy-results.repo.sarif
    category: trivy-${{ matrix.config.path }}
```

The script intentionally supports a narrow shape: SARIF 2.1.0, POSIX-relative paths, and `uriBaseId: "ROOTPATH"`. It fails before writing output for absolute paths/URLs, backslashes, repository escapes, index-only or mixed location forms, unsupported bases, pre-existing `partialFingerprints`, and malformed or ambiguous inputs. It preserves non-path fields, removes rewritten `uriBaseId` values, and removes the `ROOTPATH` base only when no reference remains.

Limits: I ran only a local synthetic test, not Trivy, the CodeQL Action, an extension, or GitHub ingestion. The caller must supply the correct scan subdirectory. Fingerprint compatibility and whether this resolves the reporter's actual upload remain unverified. This is therefore a bounded workaround to test, not a confirmed or universal fix.
