### ISSUE TITLE
[codeql-action/init] running for language `action` fails when referencing in workflow by sha rather than version.

### ISSUE THREAD

**Issue by scottschreckengaust** [github/codeql-action#2923]
When running initialization for the `action` language, the action fails to run by hash:

Works:

```yaml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3.28.19
      with:
        languages: actions
        build-mode: none
```

Fails:

```yaml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@fca7ace96b7d713c7035871441bd52efbe39e27e # v3.28.19
      with:
        languages: actions
        build-mode: none
```

A Short, Self Contained, Correct (Compilable), Example is coming...
http://sscce.org/
