### ISSUE TITLE
Append rule help text/markdown in alert view for CodeQL SARIF files

### ISSUE THREAD

**Issue by cwong-scw** [github/codeql-action#305]
In the SARIF files produced by CodeQL, the rule help text/markdown is ignored in favour of the corresponding .qhelp file content when displayed in code scanning alerts. Would it be possible to have the rule help text/markdown appended to the end of the markdown generated from the .qhelp file? This would allow any SARIF file pre-processors to enrich the displayed help text with additional material such as additional analysis results, contextual training resources, vulnerability risk ratings, etc.

**Comment by swinton** [comment]
Hey @cwong-scw. I think one way you could achieve this would be to publish [an action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action) to [GitHub's Marketplace](https://github.com/marketplace) that would perform "post-processing" of a SARIF file, before the SARIF gets uploaded to GitHub. You could use this "post-processing" step to attach additional rule help.

E.g. imagine a workflow like this, note the **`cwong-scw/post-process-sarif@v1`** step prior to the `github/codeql-action/upload-sarif@v1` step :

```yaml
name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'csharp', 'java', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        upload: false
    
    - name: Perform post-processing of CodeQL Analysis
      uses: cwong-scw/post-process-sarif@v1
      with:
        sarif_file: '../results'
    
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: '../results'

```
