### ISSUE TITLE
skipping an analysis

### ISSUE THREAD

**Issue by andy5995** [github/codeql-action#336]
Is there a place in the yml where I could add this line so I can skip an an analysis with a commit message?

`if: contains(toJson(github.event.commits), '[skip ci]') == false`

I've tried in a few different locations but I always get the error

`The workflow is not valid. .github/workflows/codeql-analysis.yml (Line: n, Col: 1): Unexpected value 'if'`

I've confirmed that if statement works with my jeyll action

```
jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip jekyll]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/docs:/srv/jekyll -v ${{ github.workspace }}/docs/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
```

**Comment by andy5995** [comment]
ok, this works

```
jobs:
  analyze:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    name: Analyze
    runs-on: ubuntu-latest
```
