### ISSUE TITLE
CodeQL 0.0.0-20201127 got error "No source code was seen during the build."

### ISSUE THREAD

**Issue by ymd-h** [github/codeql-action#353]
Hi, I am developing Python library using C++.

`CodeQL 0.0.0-20200826` didn't have any problems, however, `CodeQL 0.0.0-20201127` started getting error for `finalizing cpp`.
```
Finalizing cpp
  /opt/hostedtoolcache/CodeQL/0.0.0-20201127/x64/codeql/codeql database finalize --threads=2 /home/runner/work/_temp/codeql_databases/cpp
  No source code was seen during the build.
```
* [Last successful job](https://github.com/ymd-h/cpprb/runs/1202666085?check_suite_focus=true) (with `0.0.0-20200826`)
* [First problematic job](https://github.com/ymd-h/cpprb/runs/1604938294?check_suite_focus=true) (with `0.0.0-20201127`)

Between two jobs, only documentation was changed ([diff](https://github.com/ymd-h/cpprb/compare/5afd54b...9124049)), so that I think in principle nothing related was changed.

The following is taken from [configuration file](https://github.com/ymd-h/cpprb/blob/912404973a5e30bdb22580dd88634edf4f0693b8/.github/workflows/codeql-analysis.yml).
C++ files are also built at `pip install .`
```yaml
name: CodeQL

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: github/codeql-action/init@v1
        with:
          languages: cpp, python
          queries: +security-and-quality
      - run: pip install .
      - uses: github/codeql-action/analyze@v1
```

What are changed in between two versions `0.0.0-20200826` and `0.0.0-20201127`, and how can I manage?
(I fixed version at `v1`, however, it didn't help at all.)

**Comment by robertbrignull** [comment]
There was almost three months between those two actions runs, so there were unfortunately a lot of changes, so it'll be hard to pin down exactly what change has caused this.

However I think I know what it might be. As part of the setup for python analysis we run some `pip` commands. This installs some dependencies and makes the python analysis more accurate. My theory is that this is also building your code, but it happens before we start tracing the cpp build. This means your `pip install .` build command is not doing anything and so we say no code was seen during build, because the code is already built. The `pip install .` step only takes 5 seconds. I can't tell as I don't know your repository but Is that normal or does that seem too fast?

I did an experiment where I split the two languages into separate jobs using a matrix build. This is something we recommend doing anyway since it makes analysis faster because the two jobs run in parallel.

Try a workflow file like this:
```yaml
name: CodeQL

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ python, cpp ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality
      - run: pip install .
      - uses: github/codeql-action/analyze@v1
```

In my test on a fork of your repository, that made both languages work. There don't appear to be any alerts in the cpp code, but the analysis and upload worked.

So for now we have a workaround. I'll also make an issue internally so we can investigate this and see if there's anything we can do to avoid this bug when analysing both language together.
