### ISSUE TITLE
Document what permissions are required

### ISSUE THREAD

**Issue by brettcannon** [github/codeql-action#464]
We switched our repo to the default read-only permissions for GitHub Actions and our CodeQL workflow started to fail. Based on the failure message it seems the `statuses: write` permission is required.

P.S. Sorry to file an issue when the issue template selector only says to open an issue with GitHub Support, but none of the options really made sense since there's not "issues with a GitHub project" option.

**Comment by aeisenberg** [comment]
Thanks, @brettcannon! Let me look at that.

We should also revisit our issue templates.

**Comment by aeisenberg** [comment]
As far as I can tell, if you are using the default workflow, you _should_ only need the following permissions:

```
    permissions:
      contents: read
      security-events: write
      pull-requests: read
```

Is your workflow doing anything special?
