### ISSUE TITLE
CodeQL analysis takes a long time

### ISSUE THREAD

**Issue by endormi** [github/codeql-action#530]
I don't know whether this is specific to my project, but CodeQL analysis takes a very long time.

It's common for it take over over 3 minutes. 

This my file:

```
name: "CodeQL"

on: push
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```
