### ISSUE TITLE
Python dependency setup fails if Python 3.9 is required

### ISSUE THREAD

**Issue by timoguin** [github/codeql-action#597]
I have a library that requires Python 3.9. Although the other steps of the workflow seem to work fine, the CodeQL init step fails to install my project and its dependencies.

It seems the action has Python 3.8.5 installed. Adding support for specifying a Python version via something like [pyenv](https://github.com/pyenv/pyenv) might be the best approach to fix this issue.

### Error output

```
  The currently activated Python version 3.8.5 is not supported by the project (>=3.9,<4).
  Trying to find and use a compatible version. 
  
    NoCompatiblePythonVersionFound
  
    Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
  
    at ~/.local/lib/python3.8/site-packages/poetry/utils/env.py:736 in create_venv
         732│                     python_minor = ".".join(python_patch.split(".")[:2])
         733│                     break
         734│ 
         735│             if not executable:
      →  736│                 raise NoCompatiblePythonVersionFound(
         737│                     self._poetry.package.python_versions
         738│                 )
         739│ 
         740│         if root_venv:
  package installation with poetry failed, see error above
Warning: We were unable to install your python dependencies. You can call this action with 'setup-python-dependencies: false' to disable this process.
```

**Comment by adityasharad** [comment]
Could you please share your workflow file? Are you using `actions/setup-python` to install a specific version of Python during the workflow?

**Comment by timoguin** [comment]
> Could you please share your workflow file? Are you using `actions/setup-python` to install a specific version of Python during the workflow?

@adityasharad My workflow file is straightforward:

```yaml
name: CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1.0.3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1.0.3
```

Is this just a matter of me needing to run `actions/setup-python` prior to the CodeQL init?
