### ISSUE TITLE
Using strategy->matrix seems to duplicate scans

### ISSUE THREAD

**Issue by tunetheweb** [github/codeql-action#623]
I have the following workflow:

```yml
# Runs the CodeQL static code analysis

name: "Static Code Analysis"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**.js'
      - '**.py'
jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-20.04, windows-latest, and macos-latest
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        language: ['javascript', 'python']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt;
          # Set the `CODEQL-PYTHON` environment variable to the Python executable
          # that includes the dependencies
          echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          queries: +security-and-quality
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
```

I chose to use the strategy->matrix->language option based on [the GitHub documentation](https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed) which states:

> Using the language matrix optimizes CodeQL to run each analysis in parallel. We recommend that all workflows adopt this configuration due to the performance benefits of parallelizing builds.

This runs two jobs (one for javascript and one for python) in parallel:

![image](https://user-images.githubusercontent.com/10931297/126227864-0132423c-92d4-43e7-b9d0-870c9d9ed2da.png)

Looks good!

However, I just noticed that both those jobs run both languages:
- JavaScript - https://github.com/HTTPArchive/httparchive.org/pull/378/checks?check_run_id=3108135253
- Python - https://github.com/HTTPArchive/httparchive.org/pull/378/checks?check_run_id=3108135274

Here's the JavaScript output for example:

![image](https://user-images.githubusercontent.com/10931297/126228055-f74eb5cb-cb25-40fa-98a1-3f66f5cca490.png)

Is this the case? As it defeats the point of running them in parallel? Or have I my workflow misconfigured?

**Comment by adityasharad** [comment]
There's one element missing in your workflow: the `language` field from the matrix is unused.

Could you please try modifying your `codeql-action/init` step so that it uses only the language from the matrix, as follows?
```yaml
- name: Initialize CodeQL
  uses: github/codeql-action/init@v1
  with:
    queries: +security-and-quality
    setup-python-dependencies: false
    languages: '${{ matrix.language }}'
```

Optionally, you may wish to add the condition `if: ${{ matrix.language == 'python' }}` to your workflow steps that set up Python and Python dependencies, since you don't need those for the JavaScript analysis. This may speed things up by a few seconds but should not impact the CodeQL analysis.
