### ISSUE TITLE
Autobuild fails intermittently on Ubuntu 20.04

### ISSUE THREAD

**Issue by jasonleenaylor** [github/codeql-action#676]
We have noticed that in our CodeQL github action the autobuild fails a little less than 10% of the time. 

When it succeeds the `dotnet build --no-incremental /p:UseSharedCompilation=false` completes without error, but when it fails the logs show a successful build but there is a non 0 exit code.
The fallback to MSBuild doesn't work for our project so the autobuild eventually fails.

So far the job has always succeeded when we re-run it. 

Here is one example of the failure in our project:
https://github.com/sillsdev/TheCombine/runs/3204859583#step:4:157

**Comment by rdmarsh2** [comment]
Hi, I've passed this on to our C# team. In the meantime, would you mind adding this snippet to your CodeQL workflow after the finalize step to upload some extra logs as Actions artifacts for failed jobs?

```
- uses: actions/upload-artifact@v2
  if: ${{ failure() }}
  with:
    name: tracer-logs
    path: ${{ runner.temp }}/*.log
```
