### ISSUE TITLE
CodeQL Action omits/does not support go build tags

### ISSUE THREAD

**Issue by FloThinksPi** [github/codeql-action#847]
Given one needs go build tags to build a project. One must either specify psql or mysql depending on which db support should be compiled in. Without one of this tags there are empty modules so one gets an error while building:

```
  [2021-12-10 10:02:51] [build-stderr] 2021/12/10 10:02:51 Error running go tooling: err: exit status 1: stderr: go build github.com/cloudfoundry/go-cf-api/internal/storage/db/models: build constraints exclude all Go files in /__w/go-cf-api/go-cf-api/internal/storage/db/models
```
https://github.com/cloudfoundry/go-cf-api/runs/4481970709?check_suite_focus=true#step:8:259

Even when setting the env variable `GOTAGS=psql` in the action step it seems like this is not passed to underlying go build commands.
```
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      env:
        CGO_ENABLED: 0
        GOTAGS: 'psql,unit,integration'
```
Produces the same error.

A workaround is instead of passing the build tag into the go toolchain, to find and replace them. But this is far from being nice :).
```
    ## CodeQL does not support Go Build Tags. We need to manually strip them from files :/
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "//go:build psql"
        replace: "//"
        regex: false
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "// +build psql"
        replace: "//"
        regex: false
```

Would it be possible to pass (go) env variables to the go toolchain in the codeql-actions ?
