### ISSUE TITLE
Add support for only scanning certain directories

### ISSUE THREAD

**Issue by fishcharlie** [github/codeql-action#867]
There should be a way to only scan certain directories within my repo.

**Comment by aeisenberg** [comment]
What language are you working with? You can add configuration using `paths` and `paths-ignore` to control which directories are scanned for dynamic languages only (ie- js, ruby, python). 

See details [in the docs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan).

For compiled languages, you would need to supply your own build step where you only compile the directories you want analyzed.

**Comment by fishcharlie** [comment]
@aeisenberg Yes I'm using JavaScript & TypeScript.

So that should work. One question after reading the documentation you linked. Every code snippet under the `Example configuration files` section has a `queries` & `name` value defined. Are these required properties? Or is it allowed to **just** specify a `paths` value?

**Comment by aeisenberg** [comment]
All the properties are optional.

**Comment by aeisenberg** [comment]
Please create a new issue if you have any further questions.

**Comment by brettpostin** [comment]
I am manually building a C# (.net 4.8) solution in a subdirectory of a monorepo:

e.g.
```
    - name: Build
      run: msbuild ./Subfolder/MyProject.sln /p:platform="any cpu" /p:configuration="release"
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
```

However the analysis is still recording C# alerts in GitHub Code Scanning from other directories in the repository. How can I restrict the analysis to the subdirectory?
