### ISSUE TITLE
Code Scanning / CodeQL: analysis considers a random branch as the Base branch of our repo instead of master

### ISSUE THREAD

**Issue by doegox** [github/codeql-action#953]
Context: repo https://github.com/RfidResearchGroup/proxmark3 with `master` being the base branch displayed by default.

https://github.com/RfidResearchGroup/proxmark3/blob/master/.github/workflows/codeql-analysis.yml is referring to only master branch:
```
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '30 15 * * 4'
```

And still, see the example below, result of a commit done directly to master :
![image](https://user-images.githubusercontent.com/60773/155902506-6772f1bc-e280-4c77-a523-b77a6e76f302.png)

Worrying bits are **Base branch :question:  Not found** and the line
```
Code scanning compared refs/heads/umm_wip with refs/heads/master
```
which suggests codeql-action considers the branch `umm_wip` as being the base branch instead of `master`.

( `umm_wip` is an old branch so no codeql has ever run in it )

So it sounds like a bug to me: the analysis fails to see `master` is our Base branch and this is not a PR but a simple commit to master.
