### ISSUE TITLE
Unable to set `--max-paths` with this action

### ISSUE THREAD

**Issue by JoshuaMulliken** [github/codeql-action#962]
There is currently no way (that I could find in the documentation) to set [`--max-paths`](https://codeql.github.com/docs/codeql-cli/manual/database-analyze/#cmdoption-codeql-database-analyze-max-paths). If this is documented somewhere or would be a feature request, then please let me know!

Thanks for all the great work on this tooling!

**Comment by aibaars** [comment]
I think the following should work:
```
- name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      env: 
        CODEQL_ACTION_EXTRA_OPTIONS: '{"database":{"interpret-results":["--max-paths",0]}}'
```
