### ISSUE TITLE
Unable to set `no-run-unnecessary-builds` with this action

### ISSUE THREAD

**Issue by abstractj** [github/codeql-action#977]
Hi, I have a similar question somewhat related with #962. Running CodeQL cli it is possible to specify `--no-run-unnecessary-builds` to prevent the analysis of folders like `target` on Java. Would be possible to pass arguments to `init` like in the snippet below?

```
 - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      env: 
        CODEQL_ACTION_EXTRA_OPTIONS: '{"database":{"create":["--no-run-unnecessary-builds"]}}'
      with:
        languages: java
```

Thanks in advance.

**Comment by aeisenberg** [comment]
Yes. This should be possible. However, the action does not call `database create` directly. Instead it calls `init`, `trace-command`, and `finalize`. Both `trace-command` and `finalize` take `--no-run-unnecessary-builds` option. In your case, I'm not sure which command will be using it. It's no harm to specify it in both places, or you can try setting it in one of them first and then the other.

Something like this should work:

```yml
 - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      env: 
        CODEQL_ACTION_EXTRA_OPTIONS: '{"database":{"trace-command":["--no-run-unnecessary-builds"]},"finalize":["--no-run-unnecessary-builds"]}}'
      with:
        languages: java
```

(Check my JSON syntax since I just copy/pasted the changes.)
